// <auto-generated />
namespace DataContract.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v0alpha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v0alpha));
        
        string IMigrationMetadata.Id
        {
            get { return "201902200050359_v0.alpha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
